### ISSUE TITLE
`<jemalloc>: Unsupported system page size`

### ISSUE THREAD

**Issue by mkurz** [cagrin/azure-sql-edge-arm64#1]
Please see [my comment](https://github.com/microsoft/vscode-mssql/issues/17640#issuecomment-1496334949).
This is happening with your docker image as well. Is this something you can fix or does Microsoft come up with a fix in their image?
Thanks!

**Comment by cagrin** [comment]
This project is only ```mcr.microsoft.com/azure-sql-edge``` with couple of tools installed. If something doesn't work in the base image, it won't work in this project either. Sorry...
