### ISSUE TITLE
sqlmd commands not working on most recent release

### ISSUE THREAD

**Issue by jdalley** [cagrin/azure-sql-edge-arm64#2]
Hi there, first of all - thank you for the work you put into getting this image + sqlmd wrapper working, it's been instrumental.

I recently rebuilt my environment and grabbed the latest `cagrin/azure-sql-edge-arm64` image in my docker compose file. After the database spins up I run a command to check if it's up, however that command appears to be no longer working.
```
docker exec mydb \
  /bin/bash -c \
  "/opt/mssql-tools/bin/sqlcmd -t 60 -S 127.0.0.1,9433 -U sa -P MySecure!P@ss -Q "SET NOCOUNT ON; select 9999+9999;" 2> /dev/null"
```

On a previous image this command would return something like this:
```
-------------
        19998
```

However what I'm seeing now when I remove `2> /dev/null` is:
```
Invoke-Sqlcmd: A connection was successfully established with the server, but then an error 
occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal 
exception was caught)
Invoke-Sqlcmd: Incorrect syntax was encountered while parsing ''.
pwsh -Command 'Invoke-SqlCmd -ConnectionTimeout "60" -ServerInstance "127.0.0.1,9433"
-Username "sa" -Password "MySecure!P@ss" -Query "SET NOCOUNT ON; select 9999+9999;"'
```

Do you have any thoughts on what might have changed that could be causing this? I additionally use `sqlmd` with `-i` to load data - which I haven't tested yet but I suspect it would have a similar problem.

**Comment by andre-fagerberg** [comment]
I have a similar issue after a recent update. It seems to be related to "TrustServerCertificate=True", which should be solved using sqlcmd "-C" flag but when it gets translated to PowerShell syntax it doesn't recognise the "-C" flag. 

I had to stop using "/opt/mssql-tools/bin/sqlcmd" and instead use the equivalent command using PowerShell with the TrustServerCertificate in the ConnectionString:

`RUN pwsh -Command "Invoke-SqlCmd -ConnectionString 'Server=localhost;User Id=SA;Password=my-passord;TrustServerCertificate=True' -InputFile '/opt/mssql-scripts/scripts.sql'"`

This works fine, all my scripts run except one that sets up stored procedures.

**Comment by cagrin** [comment]
I've just released a new version that resolves missing -C option on sqlcmd wrapper.
