### ISSUE TITLE
qnap arm base

### ISSUE THREAD

**Issue by DavideSposato** [cagrin/azure-sql-edge-arm64#3]
can it work there? 
i'm tryng but the docker desn't start
it give me this message
azure-sql-edge-arm64
exec /opt/mssql/bin/permissions_check.sh: exec format error

**Comment by cagrin** [comment]
I'm afraid base image of mcr.microsoft.com/azure-sql-edge doesn't work on Qnap ARM either.

Following Microsoft's announcement, Azure SQL Edge based on ARM64 architecture is retired. See: https://techcommunity.microsoft.com/t5/sql-server-blog/azure-sql-edge-update-september-2023/ba-p/3930827

**Comment by DavideSposato** [comment]
Do you know where can i find an older version befire of the retire?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagrin** [comment]
You can try some old tags: https://mcr.microsoft.com/v2/azure-sql-edge/tags/list

**Comment by DavideSposato** [comment]
thanks, but i'm not so skilled, how should i use those tag for pull the image for container station ?
________________________________
Da: Krzysztof Strugiski ***@***.***>
Inviato: mercoledì 8 novembre 2023 11:20
A: cagrin/azure-sql-edge-arm64 ***@***.***>
Cc: Davide Sposato ***@***.***>; Author ***@***.***>
Oggetto: Re: [cagrin/azure-sql-edge-arm64] qnap arm base (Issue #3)


You can try some old tags: https://mcr.microsoft.com/v2/azure-sql-edge/tags/list<https://urldefense.com/v3/__https://mcr.microsoft.com/v2/azure-sql-edge/tags/list__;!!LFrK7YXB0Q!usxx5pZMXSX7Uhjai_Qtgf4hjcIguUZZLzv_z5QJdm3f4KGJEU7WEcu-E4zupg8n7upkf2TcQ75LMzIAAKGuFFZOzw$>

―
